   LIST P = 18f45k50
#include<p18f45k50.inc>
#include<TMR0.inc>
   ; Sección de bits de configuración inicial
    CONFIG WDTEN = OFF ; Disables the Watchdog
    CONFIG MCLRE = ON ; Enables MCLEAR
    CONFIG DEBUG = OFF ; Disables Debug mode
    CONFIG LVP = OFF ; Disables Low-Voltage programming
    CONFIG FOSC = INTOSCIO ; Enables the internal oscillator
    ; Directiva que indica en que dirección de la memoria de programa
    ; se colocará la primera instrucción
    org 0 ; Sets first instruction in address 00
    ; Declaración de variables en la memoria de datos

REGW  EQU 0x00  ; reserva 1 byte para la variable REGW
CSEG  EQU 0x01  ; reserva 1 byte para la variable CSEG      (CENTÉSIMA DE SEGUNDO)
DSEG  EQU 0x02  ; reserva 1 byte para la variable DSEG	    (DÉCIMA DE SEGUNDO)
UMIN  EQU 0x03  ; reserva 1 byte para la variable UMIN	    (UNIDAD DE MINUTO)
DMIN  EQU 0x04  ; reserva 1 byte para la variable DMIN	    (DÉCIMAS DE SEGUNDO)
LEDS  EQU 0x05  ; reserva 1 byte para la variable LEDS
LEDR  EQU 0x06  ; reserva 1 byte para la variable LEDR  (inicio/reset)
LED2  EQU 0x07  ; reserva 1 byte para la variable LED 2 
LED3  EQU 0x08  ; reserva 1 byte para la variable LED 3
LEDF  EQU 0x09  ; reserva 1 byte para la variable LED F (final)
CINCO EQU 0x0A  ; reserva 1 byte para la variable CINCO
NUEVE  EQU 0x0B  ; reserva 1 byte para la variable NUEVE
LIMPIO EQU 0x0C  ; reserva 1 byte para la variable LIMPIO
LEDSCOPY EQU 0x0D ; reserva 1 byte para la variable LEDSCOPY
LEDSCOPY2 EQU 0x0E; reserva 1 byte para la variable LEDSCOPY2
LEDSCOPY3 EQU 0x0F ; reserva 1 byte para la variable LEDSCOPY3
LEDSCOPY4 EQU 0x010 ; reserva 1 byte para la variable LEDSCOPY4
MODO EQU 0x11 ; reserva 1 byte para la variable MODO              (AJUSTE)
TIMEIO EQU 0x012 ; reserva 1 byte para la variable TIMEIO          (PARAR/COMENZAR CRONOMETRO)
TEMP1 EQU 0x19 ; reserva 1 byte para la variable TEMP1           

;VALORES 
Start:
   ; Sección de configuración del microcontrolador
   MOVLB 0x0F
   CLRF  ANSELA,1 ;PIN PORT A DIGITAL
   CLRF  ANSELB,1 ;PIN PORT B DIGITAL
   CLRF  ANSELD,1 ;PIN PORT C DIGITAL
    
   CLRF  TRISA  ; Define puerto	A como salidas (7 SEGMENTOS)
   CLRF  TRISB  ; Define puerto	B como salidas (LEDS)
   SETF  TRISD  ; Define puerto C como entradas (PUSH BUTTON)
   
   CLRF  REGW   ;LIMPIAMOS REGW
   CLRF  CSEG   ;LIMPIAMOS CSEG
   CLRF  DSEG   ;LIMPIAMOS DSEG
   CLRF  UMIN   ;LIMPIAMOS UMIN
   CLRF  DMIN   ;LIMPIAMOS DMIN
   CLRF  LEDS   ;LIMPIAMOS LEDS
   CLRF  LEDR   ;LIMPIAMOS LEDR
   CLRF  LED2   ;LIMPIAMOS LED2
   CLRF  LED3   ;LIMPIAMOS LED3
   CLRF  LEDF   ;LIMPIAMOS LEDF
   CLRF  CINCO  ;;LIMPIAMOS 5
   CLRF  NUEVE  ;LIMPIAMOS 9
   CLRF  LIMPIO ;LIMPIAMOS LIMPIO QUE SERA UNA VARIABLE EN BLANCO
   CLRF LEDSCOPY ;COPIA LED 1
   CLRF LEDSCOPY2 ;COPIA LED 2
   CLRF LEDSCOPY3 ;COPIA LED 3
   CLRF LEDSCOPY4 ;COPIA LED 4
   CLRF TIMEIO ;LIMPIA TIMEIO (0-CRONOMETRO CONTANDO      1-PARAR CRONOMETRO)
   CLRF MODO ;LIMPIA MODO (VERIFICA SI ESTA EN MODO AJUSTE  0-NO    1-SI)
   CLRF TEMP1
   
   MOVLW d'5' 
   MOVWF CINCO ;ASIGNAMOS EL VALOR DE 5
   MOVLW d'9' 
   MOVWF NUEVE ;ASIGNAMOS EL VALOR DE 9
;   MOVFF NUEVE,CSEG ;COMIENZA EN 9 LAS CENTÉSIMAS DE SEGUNDO
;   MOVFF CINCO,DSEG ;COMIENZA EN 5 LAS DÉCIMAS DE SEGUNDO
;   MOVFF NUEVE,UMIN ;COMIENZA EN 9 LAS UNIDADES DE MINUTO
;   MOVFF CINCO,DMIN ;COMIENZA EN 5 LAS DÉCIMAS DE MINUTO
   MOVLW d'5' 
   MOVWF CSEG ;COMIENZA EN 0 LAS CENTÉSIMAS DE SEGUNDO
   MOVLW d'2' 
   MOVWF DSEG ;COMIENZA EN 4 LAS DÉCIMAS DE SEGUNDO
   MOVLW d'0' 
   MOVWF UMIN ;COMIENZA EN 0 LAS UNIDADES DE MINUTO
   MOVLW d'0' 
   MOVWF DMIN ;COMIENZA EN 2 LAS DÉCIMAS DE MINUTO
   MOVFF CSEG,LEDSCOPY ;VALOR INICIAL DE CENTÉSIMAS DE SEGUNDO GUARDADO
   MOVFF DSEG,LEDSCOPY2 ;VALOR INICIAL DE DÉCIMAS DE SEGUNDO GUARDADO
   MOVFF UMIN,LEDSCOPY3 ;VALOR INICIAL DE UNIDADES DE MINUTO GUARDADO
   MOVFF DMIN,LEDSCOPY4 ;VALOR INICIAL DE DÉCIMAS DE MINUTO GUARDADO
   
   MOVLW b'00000001' 
   MOVWF LEDS ;ASIGNAMOS EL LED DE INICIO 
   MOVFF LEDS,LEDR ;ASIGNAMOS EL VALOR DE RESET DE LOS LEDS(LED 1)
   MOVLW b'00000010' 
   MOVWF LED2 ;ASIGNAMOS EL VALOR DE LED2 (LED 2)
   MOVLW b'00000100' 
   MOVWF LED3 ;ASIGNAMOS EL VALOR DE LED3 (LED 3)
   MOVLW b'00001000' 
   MOVWF LEDF ;ASIGNAMOS EL VALOR DE LEDF (LED 4)
  
   MOVLW b'01010011' ; Configures OSCCON register
   MOVWF OSCCON
 
MainLoop:
   ;BOTONES
   BTFSC PORTD,RD0 ;VERIFIVA SI EL BOTON 0 ESTA PRESIONADO
   GOTO  B0   ;INSTRUCCIONES PARA EL BOTON 1
   BTFSC PORTD,RD1 ;VERIFIVA SI EL BOTON 1 ESTA PRESIONADO
   GOTO  B1   ;INSTRUCCIONES PARA EL BOTON 1
   BTFSC PORTD,RD2 ;VERIFIVA SI EL BOTON 2 ESTA PRESIONADO
   GOTO  B2   ;INSTRUCCIONES PARA EL BOTON 2
   BTFSC PORTD,RD3 ;VERIFIVA SI EL BOTON 3 ESTA PRESIONADO
   GOTO  B3   ;INSTRUCCIONES PARA EL BOTON 3
   GOTO CAMBIO

;INDICACIONES
CAMBIO:
   TSTFSZ MODO ;VERIFICA EN QUE MODO TIENE QUE ENCENDER LOS LEDS (AJSUTE)
   CALL FLED1  ;LOS ENCIENDE EN MODO AJUSTE
   CALL FLED0 ;LOS ENCIENDE EN MODO NO AJUSTE
   ;SUBRUTINAS DE TIEMPO    
   MOVF LEDR,W ;POSICION 1ER LED
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO CSEGUNDO ;CENTÉSIMA DE SEGUNDO (0001)
   MOVF  LED2,W ;POSICION 2O LED
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO DSEGUNDO ;DÉCIMA DE SEGUNDO (0010)
   MOVF  LED3,W ;POSICION 2O LED
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO UMINUTO ;UNIDAD DE MINUTO (0100)
   GOTO DMINUTO ;DECENA DE MINUTO (1000)

    
CSEGUNDO: ;CENTÉSIMA DE SEGUNDO
   MOVF  CSEG,W  
   GOTO TIMESEG ;MOSTRARA EL VALOR EN EL 7 SEGMENTOS

DSEGUNDO: ;DÉCIMA DE SEGUNDO
   MOVF  DSEG,W  ;
   GOTO TIMESEG ;MOSTRARA EL VALOR EN EL 7 SEGMENTOS
   
UMINUTO:;UNIDAD DE MINUTO
   MOVF  UMIN,W  
   GOTO TIMESEG ;MOSTRARA EL VALOR EN EL 7 SEGMENTOS

DMINUTO:;DECENA DE MINUTO
   MOVF  DMIN,W  
   GOTO TIMESEG ;MOSTRARA EL VALOR EN EL 7 SEGMENTOS
   
;7SEGMENTOS   
TIMESEG:
   CALL  Display ;ASIGNAMOS EL VALOR DE 7 SEGMENTOS HEXADECIMAL
   MOVWF  PORTA  ;MOSTRAMOS LOS NUMEROS EN 7 SEGMENTOS   
   CALL	 Tiempo  ;DECREMENTA Y DA TIEMPO DE 1 SEG
   GOTO   MainLoop ;REGRESA A MAINLOOP
   
Display: ; 7 SEGMENTOS
   MULLW  0x02
   MOVF  PRODL,W
   ADDWF  PCL,F  ; El PCL se incrementa con el valor de
  ; W proporcionando un salto de W líneas
   RETLW  0x7E   ; Retorna con el código del 0
   RETLW  0x30   ; Retorna con el código del 1
   RETLW  0x6D   ; Retorna con el código del 2
   RETLW  0x79   ; Retorna con el código del 3
   RETLW  0x33   ; Retorna con el código del 4
   RETLW  0x5B   ; Retorna con el código del 5
   RETLW  0x5F   ; Retorna con el código del 6
   RETLW  0x70   ; Retorna con el código del 7
   RETLW  0x7F   ; Retorna con el código del 8
   RETLW  0x73   ; Retorna con el código del 9
   
   
;TIEMPO   
Tiempo:
   MOVWF  REGW  ; Guarda el registro W
   CALL REINICIO ;VERIFICA SI EL CRONOMETRO QUEDA EN (00:00) PARA REGRESAR A SUS VALORES INICIALES
   MOVF  LIMPIO,W ;PARA COMPARAR TIMEIO (EN BLANCO)
   CPFSGT TIMEIO ;VERIFICA SI PUEDE SEGUIR CONTANDO
   CALL TM0 ;CRONOMETRO
   RETURN ;REGRESA

TM0:
   ;CENTÉSIMA DE SEGUNDO 0001
   DECF  CSEG ;DECREMENTA CSEG
   MOVLW  0x0A  ;para comparar CSEG
   CPFSLT  CSEG ;Verifica que CSEG no pase de 9
   CALL TM1 
   MOVF  REGW,W  ; Se regresa el valor anterior a W
   TMR0N 0x03,0xB,0xDC ;1seg
   RETURN
    
TM1:   ;DÉCIMA DE SEGUNDO	  0010
   MOVFF NUEVE,CSEG ;reegresa al valor 9 para cuenta regresiva
   DECF	  DSEG  ;SI YA LLEGO DECREMENTA DSEG
   MOVLW  0x06  ;para comparar DSEG
   CPFSLT  DSEG ;Verifica que CSEG no pase de 6
   CALL TM2 
   RETURN
   
TM2:;UNIDAD DE MINUTO	  0100
   MOVFF  CINCO,DSEG ;reegresa al valor 5 para cuenta regresiva
   DECF	  UMIN ;SI YA LLEGO DECREMENTA UMIN
   MOVLW  0x0A ;para comparar UMIN
   CPFSLT  UMIN ;Verifica que UMIN no pase de 6
   CALL TM3
   RETURN
 
TM3: ;DECENA DE MINUTO	  1000
   MOVFF  NUEVE,UMIN ;reegresa al valor 9 para cuenta regresiva
   DECF	  DMIN  ;SI YA LLEGO DECREMENTA UMIN
   MOVLW  0x06 ;para comparar DMIN
   CPFSLT  DMIN ;Verifica que DMIN no pase de 5
   MOVFF  CINCO,DMIN ;reegresa al valor 5 para cuenta regresiva
   RETURN

;LEDS
FLED0:
   ;LEDS
   MOVLW 0x09 ;4O LED  
   CPFSLT LEDS ;COMPARAMOS PARA VER SI LLEGAMOS AL LED LIMITE (1000) 
   MOVFF LEDR,LEDS ;ASIGNAMOS EL VALOR RESET DE LOS LEDS (0001)
   MOVFF LEDS,PORTB ;MOSTRAMOS EL LED POSICION (XXXX)
   RETURN
   
FLED1:
   ;LEDS
   MOVFF LIMPIO,PORTB ;APAGA LEDS
   TMR0N 0x02,0xB,0xDC ;delay 500ms
   MOVLW 0x09 ;4O LED  
   CPFSLT LEDS ;COMPARAMOS PARA VER SI LLEGAMOS AL LED LIMITE (1000) 
   CALL fled1 ;RESET A LOS LEDS
   MOVFF LEDS,PORTB ;MOSTRAMOS EL LED POSICION (XXXX)
   RETURN

fled1:
   MOVFF LEDR,LEDS ;ASIGNAMOS EL VALOR RESET DE LOS LEDS (0001)
   CLRF MODO ;UNA VEZ TERMINADO DE RECORRER TODOS LOS LEDS EN MODO AJUSTE, SALE A MODO NO AJUSTE
   RETURN

;BOTONES
B0: ;BOTON 0 (NO INCLUDO)
  RLNCF LEDS ;ROTA LA POSICION DEL LED
  MOVFF LIMPIO,PORTB ;APAGA LOS LEDS
  TMR0N 0x02,0xB,0xDC ;delay 500ms
  GOTO MainLoop

B1: ;BOTON 1 ()AJUSTES
   TSTFSZ MODO ;VERIFICA SI EL MODO AJUSTE ESTAA ACTIVADO, SI NO ESTA LO ACTIVARA
   RLNCF LEDS   ;rotacion de los leds (0001),(0010),(0100),(1000)
   SETF MODO ;ACTIVA MODO AJUSTE
   SETF TIMEIO ;EVITA QUE EL CRONOMETRO AVANCE
   MOVFF LIMPIO,PORTB ;APAGA LOS LEDS|
   TMR0N 0x02,0xB,0xDC ;delay 500ms
   GOTO MainLoop ;REGRESA A MAINLOOP
 
B2: ; ;BOTON 2 ()INCREMENTA
   MOVF LEDR,W  ;COMIENZA EN EL LED 1 0001
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO INCCS ;incrementa centenas de segundo
   MOVF  LED2,W ;POSICION 2O LED
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO INCDS ;incrementa decenas de segundo
   MOVF  LED3,W ;POSICION 2O LED
   CPFSGT LEDS  ;VERIFICA POSICION
   GOTO INCUM ;incrementa unidades de minuto
   GOTO INCDM ;incrementa decenas de minuto

INCCS: 
    INCF CSEG ;incrementa centenas de segunddo
    TMR0N 0x02,0xB,0xDC ;delay 500ms
    MOVLW  0x0A  ;para comparar CSEG
    CPFSLT  CSEG ;Verifica que CSEG no pase de 9
    CLRF CSEG ;SI LLEGA AL LIMITE, COMIENZA DE 0
    GOTO MainLoop ;REGRESA A MAINLOOP
    
INCDS:
    INCF DSEG ;incrementa decenas de segundo
    TMR0N 0x02,0xB,0xDC ;delay 500ms
    MOVLW  0x06  ;para comparar CSEG
    CPFSLT  DSEG ;Verifica que CSEG no pase de 5
    CLRF DSEG ;SI LLEGA AL LIMITE, COMIENZA DE 0
    GOTO MainLoop ;REGRESA A MAINLOOP

INCUM:
    INCF UMIN ;incrementa unidades de minuto
    TMR0N 0x02,0xB,0xDC ;delay 500ms
    MOVLW  0x0A  ;para comparar CSEG
    CPFSLT  CSEG ;Verifica que CSEG no pase de 9
    CLRF UMIN ;SI LLEGA AL LIMITE, COMIENZA DE 0
    GOTO MainLoop ;REGRESA A MAINLOOP
 
INCDM:
    INCF DMIN ;incrementa decenas de minuto
    TMR0N 0x02,0xB,0xDC ;delay 500ms
    MOVLW  0x06  ;para comparar CSEG
    CPFSLT  DMIN ;Verifica que CSEG no pase de 5
    CLRF DMIN ;SI LLEGA AL LIMITE, COMIENZA DE 0
    GOTO MainLoop ;REGRESA A MAINLOOP
    
B3: ;BOTON 2 ()COMENZAR/DETENER CRONOMETRO
   TSTFSZ TIMEIO ;VERIFICA SI CRONOMETRO ESTA FUNCIONANDO/DETENIDO
   CALL REINICIO2  ;SI ESTA DETENIDO ACTUALIZA CALORES INICIALES
   CALL REINICIO1 ;SI ESTA FUNCIONANDO REGRESA A VALORES INICIALES
   MOVFF LIMPIO,PORTB ;APAGA LEDS
   CLRF TIMEIO ;HACE QUE EL CRONOMETRO EMPIECE A CONTAR
   MOVF LIMPIO,W  ;VERIFICA QUE ESTE EN 0
   TMR0N 0x02,0xB,0xDC ;delay 500ms
   GOTO MainLoop ;REGRESA A MAINLOOP
   
REINICIO:
   MOVF LIMPIO,W  ;VERIFICA QUE ESTE EN 0
   TSTFSZ DMIN  ;VERIFICA LAS DECENAS DE MINUTO
   RETURN
   MOVF LIMPIO,W  ;VERIFICA QUE ESTE EN 0
   TSTFSZ UMIN ;VERIFICA LAS UNIDADES DE MINUTO
   RETURN
   MOVF LIMPIO,W  ;VERIFICA QUE ESTE EN 0
   TSTFSZ DSEG ;VERIFICA LAS DECENAS DE SEGUNDO
   RETURN
   MOVF LIMPIO,W  ;VERIFICA QUE ESTE EN 0
   TSTFSZ CSEG ;VERIFICA LAS CENTENAS DE SEGUNDO
   RETURN
   CALL REINICIO1
   RETURN
  
REINICIO1: ;INICIALIZA VALORES GUARDADOS COMO ACTUALES
   MOVFF LEDSCOPY,CSEG ;REGRESAMOS AL VALOR INICIAL DE CENTÉSIMAS DE SEGUNDO 
   MOVFF LEDSCOPY2,DSEG ;REGRESAMOS AL VALOR INICIAL DE DÉCIMAS DE SEGUNDO 
   MOVFF LEDSCOPY3,UMIN ;REGRESAMOS AL VALOR INICIAL DE UNIDADES DE MINUTO 
   MOVFF LEDSCOPY4,DMIN ;REGRESAMOS AL VALOR INICIAL DE DÉCIMAS DE MINUTO 
   RETURN
   
REINICIO2: ;GUARDA VALORES ACTUALES
   MOVFF CSEG,LEDSCOPY ;VALOR INICIAL DE CENTÉSIMAS DE SEGUNDO GUARDADO
   MOVFF DSEG,LEDSCOPY2 ;VALOR INICIAL DE DÉCIMAS DE SEGUNDO GUARDADO
   MOVFF UMIN,LEDSCOPY3 ;VALOR INICIAL DE UNIDADES DE MINUTO GUARDADO
   MOVFF DMIN,LEDSCOPY4 ;VALOR INICIAL DE DÉCIMAS DE MINUTO GUARDADO
   RETURN
   
   END